/* objs */
		function Obj_3(){
			this.type="obj_3";
			this.id="";
			this.background="#fff";
			this.color="#000";
			this.border=2;
			this.border_color="#999";
			this.z_index=0;
			this.top= Math.floor(Math.random() * (254));
			this.left= Math.floor(Math.random() * (254));
			this.width=200;
			this.height=100;
			this.text='text';
			
			this.pu=null;
			this.pd=null;
			this.pl=null;
			this.pr=null;
		}

		Obj_3.prototype.pointUp=function(){
			return {'left':this.left+(this.width/4*3)/2+this.width/4,'top':this.top};
		}
		Obj_3.prototype.pointDown=function(){
			return {'left':this.left+(this.width/4*3)/2,'top':this.top+this.height};
		}
		Obj_3.prototype.pointLeft=function(){
			return {'left':this.left+this.width/8,'top':this.top+this.height/2};
		}
		Obj_3.prototype.pointRight=function(){
			return {'left':this.left+this.width/8*7,'top':this.top+this.height/2};
		}

		Obj_3.prototype.path=function(){
			ctx.lineWidth = this.border;
			ctx.beginPath();
			ctx.moveTo(this.left+this.width/4,this.top);
			ctx.lineTo(this.left,this.top+this.height);
			ctx.lineTo(this.left+this.width/4*3,this.top+this.height);
			ctx.lineTo(this.left+this.width,this.top);
			ctx.lineTo(this.left+this.width/4,this.top);
			ctx.strokeStyle="green";
			ctx.stroke();
		}
		Obj_3.prototype.selectUp=function(){
			ctx.fillStyle='yellow';
			ctx.beginPath();
			ctx.arc(this.left+(this.width/4*3)/2+this.width/4,this.top,4,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectUpOver=function(){
			ctx.fillStyle='yellow';
			ctx.beginPath();
			ctx.arc(this.left+(this.width/4*3)/2+this.width/4,this.top,10,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectDown=function(){
			ctx.fillStyle='yellow';
			ctx.beginPath();
			ctx.arc(this.left+(this.width/4*3)/2,this.top+this.height,4,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectDownOver=function(){
			ctx.fillStyle='yellow';
			ctx.beginPath();
			ctx.arc(this.left+(this.width/4*3)/2,this.top+this.height,10,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectLeft=function(){
			ctx.fillStyle='yellow';
			ctx.beginPath();
			ctx.arc(this.left+this.width/8,this.top+this.height/2,4,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}		
		Obj_3.prototype.selectLeftOver=function(){
			ctx.fillStyle='yellow';
			ctx.beginPath();
			ctx.arc(this.left+this.width/8,this.top+this.height/2,10,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectRight=function(){
			ctx.fillStyle='yellow';
			ctx.beginPath();
			ctx.arc(this.left+this.width/8*7,this.top+this.height/2,4,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectRightOver=function(){
			ctx.fillStyle='yellow';
			ctx.beginPath();
			ctx.arc(this.left+this.width/8*7,this.top+this.height/2,10,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectA=function(){
			ctx.fillStyle='blue';
			ctx.beginPath();
			ctx.arc(this.left,this.top,4,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectB=function(){
			ctx.fillStyle='blue';
			ctx.beginPath();
			ctx.arc(this.left+this.width,this.top,4,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectC=function(){
			ctx.fillStyle='blue';
			ctx.beginPath();
			ctx.arc(this.left,this.top+this.height,4,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.selectD=function(){
			ctx.fillStyle='blue';
			ctx.beginPath();
			ctx.arc(this.left+this.width,this.top+this.height,4,0,2*Math.PI);
			ctx.stroke();
			ctx.fill();
		}
		Obj_3.prototype.over=function(){
			ctx.beginPath();
			ctx.moveTo(this.left+this.width/4,this.top);
			ctx.lineTo(this.left,this.top+this.height);
			ctx.lineTo(this.left+this.width/4*3,this.top+this.height);
			ctx.lineTo(this.left+this.width,this.top);
			ctx.lineTo(this.left+this.width/4,this.top);
			ctx.strokeStyle="blue";
			ctx.stroke();
			this.selectUp();
			this.selectDown();
			this.selectLeft();
			this.selectRight();
			this.selectA();
			this.selectB();
			this.selectC();
			this.selectD();
		}
		Obj_3.prototype.select=function(){
			ctx.lineWidth = this.border;
			ctx.beginPath();
			ctx.moveTo(this.left+this.width/4,this.top);
			ctx.lineTo(this.left,this.top+this.height);
			ctx.lineTo(this.left+this.width/4*3,this.top+this.height);
			ctx.lineTo(this.left+this.width,this.top);
			ctx.lineTo(this.left+this.width/4,this.top);
			ctx.strokeStyle="red";
			ctx.stroke();
			ctx.lineWidth = 1;
			ctx.beginPath();
			ctx.moveTo(this.left,this.top);
			ctx.lineTo(this.left,this.top+this.height);
			ctx.lineTo(this.left+this.width,this.top+this.height);
			ctx.lineTo(this.left+this.width,this.top+this.height);
			ctx.lineTo(this.left+this.width,this.top);
			ctx.lineTo(this.left,this.top);
			ctx.strokeStyle="blue";
			ctx.stroke();
			//   select
			this.selectUp();
			this.selectDown();
			this.selectLeft();
			this.selectRight();
			this.selectA();
			this.selectB();
			this.selectC();
			this.selectD();
			//
		}
		Obj_3.prototype.prinText=function(){
			ctx.font="14px Georgia";
			ctx.fillStyle=this.color;
			ctx.fillText(this.text,this.left+this.border+this.width/2,this.top+this.border+this.height/2);
		}
		Obj_3.prototype.update=function(){
			this.path();
			this.prinText();
			if(this==select_obj&&this.pr!=null){
				eval('this.prline.move'+this.prat+'(this.pointRight().left,this.pointRight().top)');
			}
			if(this==select_obj&&this.pu!=null){
				eval('this.puline.move'+this.puat+'(this.pointUp().left,this.pointUp().top)');
			}
			if(this==select_obj&&this.pl!=null){		
				eval('this.plline.move'+this.plat+'(this.pointLeft().left,this.pointLeft().top)');
			}
			if(this==select_obj&&this.pd!=null){		
				eval('this.pdline.move'+this.pdat+'(this.pointDown().left,this.pointDown().top)');
			}
		}
		//
